/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, ApkInfo as PrismaApkInfo } from "@prisma/client";

export class ApkInfoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ApkInfoCountArgs, "select">): Promise<number> {
    return this.prisma.apkInfo.count(args);
  }

  async apkInfos(args: Prisma.ApkInfoFindManyArgs): Promise<PrismaApkInfo[]> {
    return this.prisma.apkInfo.findMany(args);
  }
  async apkInfo(
    args: Prisma.ApkInfoFindUniqueArgs
  ): Promise<PrismaApkInfo | null> {
    return this.prisma.apkInfo.findUnique(args);
  }
  async createApkInfo(args: Prisma.ApkInfoCreateArgs): Promise<PrismaApkInfo> {
    return this.prisma.apkInfo.create(args);
  }
  async updateApkInfo(args: Prisma.ApkInfoUpdateArgs): Promise<PrismaApkInfo> {
    return this.prisma.apkInfo.update(args);
  }
  async deleteApkInfo(args: Prisma.ApkInfoDeleteArgs): Promise<PrismaApkInfo> {
    return this.prisma.apkInfo.delete(args);
  }
}
